msg: "anubhav - now working  actuator was missed and at .props should include/enable= refresh at actuator config"
info: "u should put server.port in app bcos what config server says"
# Add any other app-specific properties here
